spring:
  datasource:
    url: jdbc:h2:mem:itachi #jdbc url
    platform: h2
    #username: itachi
    #password: itachi
  h2:
    console:
      enabled: true

#slf4j config
logging:
  level:
    com.itachi.ekart: DEBUG
  pattern:
    console: "[%-5p] [%d{dd HH:mm:ss}] [%F#%L] [%3C-%M] -%m%n"  #p priority, d{} date{formate}, F filename, L lineNo, C FullClass, M method, m msg, n newline
    file: "[%-5p] [%d{dd HH:mm:ss}] [%F#%L] [%3C-%M] -%m%n"





management:
  endpoint:
    health:
      show-details: always
