
#slf4j config
logging:
  level:
    com.itachi.ekart: DEBUG
  pattern:
    console: "[%-5p] [%d{dd HH:mm:ss}] [%F#%L] [%3C-%M] -%m%n"  #p priority, d{} date{formate}, F filename, L lineNo, C FullClass, M method, m msg, n newline
    file: "[%-5p] [%d{dd HH:mm:ss}] [%F#%L] [%3C-%M] -%m%n"
<<<<<<< HEAD:application.yml





management:
  endpoint:
    health:
      show-details: always
=======
  file:
    path: ./SL4jLog/
    name: log.txt
>>>>>>> 904704538b1e9510b4679a7c056d3a493f0665b2:application-dev.yml
